<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['name' => 'Afghan', 'nationality' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Albanian', 'nationality' => 'Albania', 'code' => 'AL'],
            ['name' => 'Algerian', 'nationality' => 'Algeria', 'code' => 'DZ'],
            ['name' => 'Andorran', 'nationality' => 'Andorra', 'code' => 'AD'],
            ['name' => 'Angolan', 'nationality' => 'Angola', 'code' => 'AO'],
            ['name' => 'Antiguan or Barbudan', 'nationality' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['name' => 'Argentine', 'nationality' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Armenian', 'nationality' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Australian', 'nationality' => 'Australia', 'code' => 'AU'],
            ['name' => 'Austrian', 'nationality' => 'Austria', 'code' => 'AT'],
            ['name' => 'Azerbaijani', 'nationality' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Bahamian', 'nationality' => 'Bahamas', 'code' => 'BS'],
            ['name' => 'Bahraini', 'nationality' => 'Bahrain', 'code' => 'BH'],
            ['name' => 'Bangladeshi', 'nationality' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Barbadian', 'nationality' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belarusian', 'nationality' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Belgian', 'nationality' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Belizean', 'nationality' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Beninese', 'nationality' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Bhutanese', 'nationality' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Bolivian', 'nationality' => 'Bolivia', 'code' => 'BO'],
            ['name' => 'Bosnian', 'nationality' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'Botswanan', 'nationality' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Brazilian', 'nationality' => 'Brazil', 'code' => 'BR'],
            ['name' => 'Bruneian', 'nationality' => 'Brunei Darussalam', 'code' => 'BN'],
            ['name' => 'Bulgarian', 'nationality' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Burkinabe', 'nationality' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundian', 'nationality' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Cabo Verdean', 'nationality' => 'Cabo Verde', 'code' => 'CV'],
            ['name' => 'Cambodian', 'nationality' => 'Cambodia', 'code' => 'KH'],
            ['name' => 'Cameroonian', 'nationality' => 'Cameroon', 'code' => 'CM'],
            ['name' => 'Canadian', 'nationality' => 'Canada', 'code' => 'CA'],
            ['name' => 'Central African', 'nationality' => 'Central African Republic', 'code' => 'CF'],
            ['name' => 'Chadian', 'nationality' => 'Chad', 'code' => 'TD'],
            ['name' => 'Chilean', 'nationality' => 'Chile', 'code' => 'CL'],
            ['name' => 'Chinese', 'nationality' => 'China', 'code' => 'CN'],
            ['name' => 'Colombian', 'nationality' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Comorian', 'nationality' => 'Comoros', 'code' => 'KM'],
            ['name' => 'Congolese', 'nationality' => 'Congo', 'code' => 'CG'],
            ['name' => 'Congolese (Democratic Republic)', 'nationality' => 'Congo (Democratic Republic)', 'code' => 'CD'],
            ['name' => 'Costa Rican', 'nationality' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Croatian', 'nationality' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Cuban', 'nationality' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Cypriot', 'nationality' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Czech', 'nationality' => 'Czech Republic', 'code' => 'CZ'],
            ['name' => 'Danish', 'nationality' => 'Denmark', 'code' => 'DK'],
            ['name' => 'Djiboutian', 'nationality' => 'Djibouti', 'code' => 'DJ'],
            ['name' => 'Dominican', 'nationality' => 'Dominica', 'code' => 'DM'],
            ['name' => 'Dominican', 'nationality' => 'Dominican Republic', 'code' => 'DO'],
            ['name' => 'Ecuadorian', 'nationality' => 'Ecuador', 'code' => 'EC'],
            ['name' => 'Egyptian', 'nationality' => 'Egypt', 'code' => 'EG'],
            ['name' => 'Salvadoran', 'nationality' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Equatorial Guinean', 'nationality' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['name' => 'Eritrean', 'nationality' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Estonian', 'nationality' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Eswatini', 'nationality' => 'Eswatini', 'code' => 'SZ'],
            ['name' => 'Ethiopian', 'nationality' => 'Ethiopia', 'code' => 'ET'],
            ['name' => 'Fijian', 'nationality' => 'Fiji', 'code' => 'FJ'],
            ['name' => 'Finnish', 'nationality' => 'Finland', 'code' => 'FI'],
            ['name' => 'French', 'nationality' => 'France', 'code' => 'FR'],
            ['name' => 'Gabonese', 'nationality' => 'Gabon', 'code' => 'GA'],
            ['name' => 'Gambian', 'nationality' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Georgian', 'nationality' => 'Georgia', 'code' => 'GE'],
            ['name' => 'German', 'nationality' => 'Germany', 'code' => 'DE'],
            ['name' => 'Ghanian', 'nationality' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Greek', 'nationality' => 'Greece', 'code' => 'GR'],
            ['name' => 'Grenadian', 'nationality' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Guatemalan', 'nationality' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guinean', 'nationality' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bissauan', 'nationality' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Guyanese', 'nationality' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haitian', 'nationality' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Honduran', 'nationality' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Hungarian', 'nationality' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Icelander', 'nationality' => 'Iceland', 'code' => 'IS'],
            ['name' => 'Indian', 'nationality' => 'India', 'code' => 'IN'],
            ['name' => 'Indonesian', 'nationality' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Iranian', 'nationality' => 'Iran', 'code' => 'IR'],
            ['name' => 'Iraqi', 'nationality' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Irish', 'nationality' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Israeli', 'nationality' => 'Israel', 'code' => 'IL'],
            ['name' => 'Italian', 'nationality' => 'Italy', 'code' => 'IT'],
            ['name' => 'Ivorian', 'nationality' => 'Ivory Coast', 'code' => 'CI'],
            ['name' => 'Jamaican', 'nationality' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Japanese', 'nationality' => 'Japan', 'code' => 'JP'],
            ['name' => 'Jordanian', 'nationality' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Kazakhstani', 'nationality' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Kenyan', 'nationality' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Kiribati', 'nationality' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'Kittian and Nevisian', 'nationality' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['name' => 'Kuwaiti', 'nationality' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Kyrgyzstani', 'nationality' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Laotian', 'nationality' => 'Laos', 'code' => 'LA'],
            ['name' => 'Latvian', 'nationality' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Lebanese', 'nationality' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Lesotho', 'nationality' => 'Lesotho', 'code' => 'LS'],
            ['name' => 'Liberian', 'nationality' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Libyan', 'nationality' => 'Libya', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'nationality' => 'Liechtenstein', 'code' => 'LI'],
            ['name' => 'Lithuanian', 'nationality' => 'Lithuania', 'code' => 'LT'],
            ['name' => 'Luxembourgian', 'nationality' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Macedonian', 'nationality' => 'North Macedonia', 'code' => 'MK'],
            ['name' => 'Madagascan', 'nationality' => 'Madagascar', 'code' => 'MG'],
            ['name' => 'Malawian', 'nationality' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Malaysian', 'nationality' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Maldivian', 'nationality' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Malian', 'nationality' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'nationality' => 'Malta', 'code' => 'MT'],
            ['name' => 'Mauritanian', 'nationality' => 'Mauritania', 'code' => 'MR'],
            ['name' => 'Mauritian', 'nationality' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Mexican', 'nationality' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Micronesian', 'nationality' => 'Micronesia', 'code' => 'FM'],
            ['name' => 'Moldovan', 'nationality' => 'Moldova', 'code' => 'MD'],
            ['name' => 'Monacan', 'nationality' => 'Monaco', 'code' => 'MC'],
            ['name' => 'Mongolian', 'nationality' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Montenegrin', 'nationality' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Moroccan', 'nationality' => 'Morocco', 'code' => 'MA'],
            ['name' => 'Mozambican', 'nationality' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Namibian', 'nationality' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Nauruan', 'nationality' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepali', 'nationality' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Netherlandic', 'nationality' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'New Zealand', 'nationality' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Nicaraguan', 'nationality' => 'Nicaragua', 'code' => 'NI'],
            ['name' => 'Nigerien', 'nationality' => 'Niger', 'code' => 'NE'],
            ['name' => 'Nigerian', 'nationality' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'North Korean', 'nationality' => 'North Korea', 'code' => 'KP'],
            ['name' => 'Norwegian', 'nationality' => 'Norway', 'code' => 'NO'],
            ['name' => 'Omani', 'nationality' => 'Oman', 'code' => 'OM'],
            ['name' => 'Pakistani', 'nationality' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Palauan', 'nationality' => 'Palau', 'code' => 'PW'],
            ['name' => 'Panamanian', 'nationality' => 'Panama', 'code' => 'PA'],
            ['name' => 'Papua New Guinean', 'nationality' => 'Papua New Guinea', 'code' => 'PG'],
            ['name' => 'Paraguayan', 'nationality' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Peruvian', 'nationality' => 'Peru', 'code' => 'PE'],
            ['name' => 'Philippine', 'nationality' => 'Philippines', 'code' => 'PH'],
            ['name' => 'Polish', 'nationality' => 'Poland', 'code' => 'PL'],
            ['name' => 'Portuguese', 'nationality' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Qatari', 'nationality' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Romanian', 'nationality' => 'Romania', 'code' => 'RO'],
            ['name' => 'Russian', 'nationality' => 'Russia', 'code' => 'RU'],
            ['name' => 'Rwandan', 'nationality' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Saint Kitts and Nevis', 'nationality' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['name' => 'Saint Lucian', 'nationality' => 'Saint Lucia', 'code' => 'LC'],
            ['name' => 'Saint Vincentian', 'nationality' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['name' => 'Samoan', 'nationality' => 'Samoa', 'code' => 'WS'],
            ['name' => 'San Marinese', 'nationality' => 'San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tomean', 'nationality' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['name' => 'Saudi Arabian', 'nationality' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Senegalese', 'nationality' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Serbian', 'nationality' => 'Serbia', 'code' => 'RS'],
            ['name' => 'Seychellois', 'nationality' => 'Seychelles', 'code' => 'SC'],
            ['name' => 'Sierra Leonean', 'nationality' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singaporean', 'nationality' => 'Singapore', 'code' => 'SG'],
            ['name' => 'Slovak', 'nationality' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Slovenian', 'nationality' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Solomon Islander', 'nationality' => 'Solomon Islands', 'code' => 'SB'],
            ['name' => 'Somali', 'nationality' => 'Somalia', 'code' => 'SO'],
            ['name' => 'South African', 'nationality' => 'South Africa', 'code' => 'ZA'],
            ['name' => 'South Korean', 'nationality' => 'South Korea', 'code' => 'KR'],
            ['name' => 'South Sudanese', 'nationality' => 'South Sudan', 'code' => 'SS'],
            ['name' => 'Spanish', 'nationality' => 'Spain', 'code' => 'ES'],
            ['name' => 'Sri Lankan', 'nationality' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Sudanese', 'nationality' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Surinamese', 'nationality' => 'Suriname', 'code' => 'SR'],
            ['name' => 'Swazi', 'nationality' => 'Eswatini', 'code' => 'SZ'],
            ['name' => 'Swedish', 'nationality' => 'Sweden', 'code' => 'SE'],
            ['name' => 'Swiss', 'nationality' => 'Switzerland', 'code' => 'CH'],
            ['name' => 'Syrian', 'nationality' => 'Syria', 'code' => 'SY'],
            ['name' => 'Taiwanese', 'nationality' => 'Taiwan', 'code' => 'TW'],
            ['name' => 'Tajikistani', 'nationality' => 'Tajikistan', 'code' => 'TJ'],
            ['name' => 'Tanzanian', 'nationality' => 'Tanzania', 'code' => 'TZ'],
            ['name' => 'Thai', 'nationality' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Togolese', 'nationality' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tongan', 'nationality' => 'Tonga', 'code' => 'TO'],
            ['name' => 'Trinidadian or Tobagonian', 'nationality' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['name' => 'Tunisian', 'nationality' => 'Tunisia', 'code' => 'TN'],
            ['name' => 'Turkmen', 'nationality' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Tugrik', 'nationality' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Tuvaluan', 'nationality' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Ugandan', 'nationality' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukrainian', 'nationality' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'Uruguayan', 'nationality' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistani', 'nationality' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Vanuatuan', 'nationality' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Venezuelan', 'nationality' => 'Venezuela', 'code' => 'VE'],
            ['name' => 'Vietnamese', 'nationality' => 'Vietnam', 'code' => 'VN'],
            ['name' => 'Yemenite', 'nationality' => 'Yemen', 'code' => 'YE'],
            ['name' => 'Zambian', 'nationality' => 'Zambia', 'code' => 'ZM'],
            ['name' => 'Zimbabwean', 'nationality' => 'Zimbabwe', 'code' => 'ZW'],
        ];
        

        // Insert into the countries table
        DB::table('nationalities')->insert($nationalities);
    }
}
